// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAZlvUWcchmaXFWGT6RFvJiaR1UJ_Yur38',
  appId: '1:1009900446483:android:03520d2451b8201f8bb0e6',
  messagingSenderId: '1009900446483',
  projectId: 'deshiponnos',
  databaseURL:
      'https://deshiponnos-default-rtdb.asia-southeast1.firebasedatabase.app',
  storageBucket: 'deshiponnos.appspot.com',
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rLI-kw2YRz3nB2fmQE_waBi-W8AWI9o',
    appId: '1:1009900446483:web:ae3523a127f331ad8bb0e6',
    messagingSenderId: '1009900446483',
    projectId: 'deshiponnos',
    authDomain: 'deshiponnos.firebaseapp.com',
    databaseURL:
        'https://deshiponnos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'deshiponnos.appspot.com',
    measurementId: 'G-3MMNZ0DX75',
  );
}
