// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rLI-kw2YRz3nB2fmQE_waBi-W8AWI9o',
    appId: '1:1009900446483:web:ae3523a127f331ad8bb0e6',
    messagingSenderId: '1009900446483',
    projectId: 'deshiponnos',
    authDomain: 'deshiponnos.firebaseapp.com',
    storageBucket: 'deshiponnos.appspot.com',
    measurementId: 'G-3MMNZ0DX75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZlvUWcchmaXFWGT6RFvJiaR1UJ_Yur38',
    appId: '1:1009900446483:android:f78cc2bd4e60acdb8bb0e6',
    messagingSenderId: '1009900446483',
    projectId: 'deshiponnos',
    storageBucket: 'deshiponnos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_MixRM3LLfUcVUxhQ_sIJb1ls5c4tAY',
    appId: '1:1009900446483:ios:fd8cd35074ce08778bb0e6',
    messagingSenderId: '1009900446483',
    projectId: 'deshiponnos',
    storageBucket: 'deshiponnos.appspot.com',
    iosBundleId: 'com.example.deshiPonno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_MixRM3LLfUcVUxhQ_sIJb1ls5c4tAY',
    appId: '1:1009900446483:ios:53e654c1be2188408bb0e6',
    messagingSenderId: '1009900446483',
    projectId: 'deshiponnos',
    storageBucket: 'deshiponnos.appspot.com',
    iosBundleId: 'com.example.deshiPonno.RunnerTests',
  );
}
